name: "Create Flake update"
on:
  workflow_dispatch: 

permissions:
  pull-requests: write

jobs:
  create-flake-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v14
        with:
          name: kranners
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      - name: Create Flake PR
        run: |
          git config --global user.email "flake-updater@cute.engineer"
          git config --global user.name "Flake Updater"
          FLAKE_BRANCH_NAME="flake-update-${{ steps.date.outputs.date }}"
          git switch --create "$FLAKE_BRANCH_NAME"
          nix flake update
          git commit -am "Flake update"
          git push -u origin "$FLAKE_BRANCH_NAME"
          gh pr create --base main --title "Flake update $(date +'%Y-%m-%dT%H-%M-%S')" --body "Created by a GitHub Action."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

