name: "Check flake"
on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v14
      with:
        name: kranners
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: |
        cachix watch-store kranners &
        nix flake check --show-trace

